version: '3'
services:
  elixir_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:     # Docker need to expose ports for you to access your app.
      - 4000:4000
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
